--
-- SQL Instructions for profiling the DGERT Data 
--

.mode csv
.import ./CSV-files/ALTERACOES_ESTATUTOS.csv TEMP_ALTERACOES_ESTATUTOS
.import ./CSV-files/ELEICAO_CORPOS_GERENTES.csv TEMP_ELEICAO_CORPOS_GERENTES
.import ./CSV-files/ENTIDADES.csv TEMP_ENTIDADES
.import ./CSV-files/PROCESSOS.csv TEMP_PROCESSOS

UPDATE TEMP_ENTIDADES SET NOME_ENTIDADE = trim(replace(replace(replace(NOME_ENTIDADE, X'0A', ' '),'  ',' '),'  ',' '));
UPDATE TEMP_ENTIDADES SET SIGLA = trim(replace(replace(replace(SIGLA, X'0A', ' '),'  ',' '),'  ',' '));

UPDATE TEMP_ENTIDADES SET NOME_ENTIDADE = replace(NOME_ENTIDADE,' NAC. ',' NACIONAL ')  WHERE instr(NOME_ENTIDADE, ' NAC. ') > 0;
UPDATE TEMP_ENTIDADES SET NOME_ENTIDADE = replace(NOME_ENTIDADE,' TRAB. ',' TRABALHADORES ')  WHERE instr(NOME_ENTIDADE, ' TRAB. ') > 0;
UPDATE TEMP_ENTIDADES SET NOME_ENTIDADE = replace(NOME_ENTIDADE,' DO DIST. D',' DO DISTRITO D')  WHERE instr(NOME_ENTIDADE, ' DO DIST. D') > 0;
UPDATE TEMP_ENTIDADES SET NOME_ENTIDADE = replace(NOME_ENTIDADE,' DOS DIST. ',' DO DISTRITOS ')  WHERE instr(NOME_ENTIDADE, ' DOS DIST. ') > 0;
UPDATE TEMP_ENTIDADES SET NOME_ENTIDADE = replace(NOME_ENTIDADE,' DA IND. ',' DA INDÚSTRIA ')  WHERE instr(NOME_ENTIDADE, ' DA IND. ') > 0;
UPDATE TEMP_ENTIDADES SET NOME_ENTIDADE = replace(NOME_ENTIDADE,' DAS IND. ',' DAS INDÚSTRIAS ')  WHERE instr(NOME_ENTIDADE, ' DAS IND. ') > 0;
UPDATE TEMP_ENTIDADES SET NOME_ENTIDADE = replace(NOME_ENTIDADE,' DOS SIND. ',' DOS SINDICATOS ')  WHERE instr(NOME_ENTIDADE, ' DOS SIND. ') > 0;
UPDATE TEMP_ENTIDADES SET NOME_ENTIDADE = replace(NOME_ENTIDADE,'SIND. ','SINDICATO ')  WHERE instr(NOME_ENTIDADE, 'SIND. ') > 0;
UPDATE TEMP_ENTIDADES SET NOME_ENTIDADE = replace(NOME_ENTIDADE,'ASS. ','ASSOCIAÇÃO ')  WHERE instr(NOME_ENTIDADE, 'ASS. ') > 0;
UPDATE TEMP_ENTIDADES SET NOME_ENTIDADE = replace(NOME_ENTIDADE,'ASSOC. ','ASSOCIAÇÃO ')  WHERE instr(NOME_ENTIDADE, 'ASSOC. ') > 0;
UPDATE TEMP_ENTIDADES SET NOME_ENTIDADE = replace(NOME_ENTIDADE,'FED. ','FEDERAÇÃO ')  WHERE instr(NOME_ENTIDADE, 'FED. ') > 0;

-- Contar quantas entidades existem e quantos nomes distintos
SELECT COUNT(DISTINCT ID_ENTIDADE) AS ENTIDADES, COUNT(DISTINCT NOME_ENTIDADE) AS NOMES FROM TEMP_ENTIDADES;

-- Contar quantas entidades (e nomes de entidades) têm uma sigla defenida
SELECT COUNT(DISTINCT ID_ENTIDADE) AS ENTIDADES, COUNT(DISTINCT NOME_ENTIDADE) AS NOMES  FROM TEMP_ENTIDADES WHERE SIGLA IS NOT NULL AND SIGLA <> '';

-- Contar quantas entidades é que têm um nome repetido na tabela original.
SELECT COUNT(DISTINCT ID_ENTIDADE) AS ENTIDADES, NOME_ENTIDADE FROM TEMP_ENTIDADES GROUP BY NOME_ENTIDADE HAVING COUNT(*) > 1;

-- Contar quantas entidades é que têm um hifen como parte do nome, potencialmente indicando que a sigla é dada em conjunto com o nome.
SELECT COUNT(DISTINCT ID_ENTIDADE) AS ENTIDADES, COUNT(DISTINCT NOME_ENTIDADE) AS NOMES, 'Com Sigla Definida'  FROM TEMP_ENTIDADES WHERE SIGLA IS NOT NULL AND SIGLA <> '' AND instr(NOME_ENTIDADE, ' - ') > 0
UNION
SELECT COUNT(DISTINCT ID_ENTIDADE) AS ENTIDADES, COUNT(DISTINCT NOME_ENTIDADE) AS NOMES, 'Sem Sigla Definida'  FROM TEMP_ENTIDADES WHERE (SIGLA IS NULL OR SIGLA = '') AND instr(NOME_ENTIDADE, ' - ') > 0;

-- Contar quantas entidades é que têm as palavras CGTP, C.G.T.P, UGT, ou U.G.T. como parte do nome.
SELECT COUNT(DISTINCT ID_ENTIDADE) AS ENTIDADES, COUNT(DISTINCT NOME_ENTIDADE) AS NOMES, 'Com Sigla Definida'  FROM TEMP_ENTIDADES WHERE SIGLA IS NOT NULL AND SIGLA <> '' AND (instr(NOME_ENTIDADE, ' CGTP') > 0 OR instr(NOME_ENTIDADE, 'CGTP ') OR instr(NOME_ENTIDADE, ' UGT') > 0 OR instr(NOME_ENTIDADE, 'UGT ') OR instr(NOME_ENTIDADE, ' C.G.T.P.') > 0 OR instr(NOME_ENTIDADE, 'C.G.T.P. ') OR instr(NOME_ENTIDADE, ' U.G.T.') > 0 OR instr(NOME_ENTIDADE, 'U.G.T. '))
UNION
SELECT COUNT(DISTINCT ID_ENTIDADE) AS ENTIDADES, COUNT(DISTINCT NOME_ENTIDADE) AS NOMES, 'Sem Sigla Definida'  FROM TEMP_ENTIDADES WHERE (SIGLA IS NULL OR SIGLA = '') AND (instr(NOME_ENTIDADE, ' CGTP') > 0 OR instr(NOME_ENTIDADE, 'CGTP ') OR instr(NOME_ENTIDADE, ' UGT') > 0 OR instr(NOME_ENTIDADE, 'UGT ') OR instr(NOME_ENTIDADE, ' C.G.T.P.') > 0 OR instr(NOME_ENTIDADE, 'C.G.T.P. ') OR instr(NOME_ENTIDADE, ' U.G.T.') > 0 OR instr(NOME_ENTIDADE, 'U.G.T. '));

-- Contar quantas entidades é que têm um ponto final como parte do nome, potencialmente indicando uma abreviatura.
SELECT COUNT(DISTINCT ID_ENTIDADE) AS ENTIDADES, COUNT(DISTINCT NOME_ENTIDADE) AS NOMES, 'Com Sigla Definida'  FROM TEMP_ENTIDADES WHERE SIGLA IS NOT NULL AND SIGLA <> '' AND instr(NOME_ENTIDADE, '.') > 0
UNION
SELECT COUNT(DISTINCT ID_ENTIDADE) AS ENTIDADES, COUNT(DISTINCT NOME_ENTIDADE) AS NOMES, 'Sem Sigla Definida'  FROM TEMP_ENTIDADES WHERE (SIGLA IS NULL OR SIGLA = '') AND instr(NOME_ENTIDADE, '.') > 0;

-- Contar quantas entidades sindicais é que não têm uma entrada correspondente na tabela das mudanças de estatutos.
SELECT COUNT(DISTINCT ID_ENTIDADE) AS ENTIDADES, COUNT(DISTINCT NOME_ENTIDADE) AS NOMES
FROM TEMP_ENTIDADES
WHERE ID_ENTIDADE NOT IN ( SELECT ID_ENTIDADE FROM TEMP_ALTERACOES_ESTATUTOS) AND instr(NOME_ENTIDADE, 'SIND') > 0;

-- Contar quantas entidades sindicais é que não têm uma entrada correspondente na tabela das eleições.
SELECT COUNT(DISTINCT ID_ENTIDADE) AS ENTIDADES, COUNT(DISTINCT NOME_ENTIDADE) AS NOMES
FROM TEMP_ENTIDADES
WHERE ID_ENTIDADE NOT IN ( SELECT ID_ENTIDADE FROM TEMP_ELEICAO_CORPOS_GERENTES) AND instr(NOME_ENTIDADE, 'SIND') > 0;

-- Contar quantas entidades é que têm uma entrada correspondente na tabela das mudanças de estatutos, correspondente a um processo com o código da criaçaõ de entidade sindical/patronal.
SELECT COUNT(DISTINCT ID_ENTIDADE) AS ENTIDADES, COUNT(DISTINCT NOME_ENTIDADE) AS NOMES
FROM TEMP_ENTIDADES
WHERE ID_ENTIDADE IN ( SELECT ID_ENTIDADE FROM TEMP_ALTERACOES_ESTATUTOS NATURAL JOIN TEMP_PROCESSOS WHERE PROCESSO LIKE '2.4.13%' OR PROCESSO LIKE '2.5.13%');

-- Contar quantas entidades é que têm uma entrada correspondente na tabela das mudanças de estatutos, correspondente a um processo com o código da extinção de entidade sindical/patronal.
SELECT COUNT(DISTINCT ID_ENTIDADE) AS ENTIDADES, COUNT(DISTINCT NOME_ENTIDADE) AS NOMES
FROM TEMP_ENTIDADES
WHERE ID_ENTIDADE IN ( SELECT ID_ENTIDADE FROM TEMP_ALTERACOES_ESTATUTOS NATURAL JOIN TEMP_PROCESSOS WHERE PROCESSO LIKE '2.4.18%' OR PROCESSO LIKE '2.5.18%');

-- Contar quantas entidades é que têm várias entradas na tabela das mudanças de estatutos, indicando um âmbito geográfico diferente.
SELECT COUNT(*) 
FROM (
 SELECT DISTINCT ID_ENTIDADE, NOME_ENTIDADE
 FROM TEMP_ENTIDADES NATURAL JOIN (SELECT DISTINCT ID_ENTIDADE, AMBITO_GEOGRAFICO FROM TEMP_ALTERACOES_ESTATUTOS WHERE trim(AMBITO_GEOGRAFICO) <> '')
 GROUP BY ID_ENTIDADE, NOME_ENTIDADE
 HAVING COUNT(DISTINCT AMBITO_GEOGRAFICO) > 1
) ORDER BY ID_ENTIDADE;

-- Contar numero de entidades sindicais activas a cada ano registado na base de dados
--SELECT ANO, COUNT(DISTINCT ID)
--FROM Org_Sindical, (
--  SELECT DISTINCT CAST(strftime('%Y',date(Data_Primeira_Actividade)) AS DECIMAL) AS Ano FROM Org_Sindical WHERE Data_Primeira_Actividade IS NOT NULL
--  UNION
--  SELECT DISTINCT CAST(strftime('%Y',date(Data_Ultima_Actividade)) AS DECIMAL) AS Ano FROM Org_Sindical WHERE Data_Primeira_Actividade IS NOT NULL ) AS ANOS
--WHERE CAST(strftime('%Y',date(Data_Primeira_Actividade)) AS DECIMAL) <= ANO AND (Activa = 1 OR CAST(strftime('%Y',date(Data_Ultima_Actividade)) AS DECIMAL) >= ANO )
--GROUP BY ANO;

DROP TABLE TEMP_ALTERACOES_ESTATUTOS;
DROP TABLE TEMP_ELEICAO_CORPOS_GERENTES;
DROP TABLE TEMP_ENTIDADES;
DROP TABLE TEMP_PROCESSOS;